---
title: "Normal distribution"
---

```{r, include=FALSE}
library(exams)
library(mathml)
library(mistakes)

task <- "ipnorm"
rolog::usemodule(system.file("rexams/ipnorm.pl", package="mistakes"))

hook(pvalue(.P), .P)
hook(pnorm1(.X, .Tail), pnorm(.X, .Tail))
hook(z1, z[1L])
hook(z2, z[2L])

dist <- function(Symb, X, Tail)
  return(X)

tail <- function(Tail)
  return(Tail)

pnorm1 <- function(C, Tail)
{
  if(Tail == "lower")
    return(pnorm(C, lower.tail=TRUE))

  if(Tail == "upper")
    return(pnorm(C, lower.tail=FALSE))

  stop("Tail must bei either upper or lower")
}

## DATA GENERATION
repeat
{
  mu <- round(runif(1, min=-10, max=10), 1)
  sigma <- round(runif(1, min=5, max=25), 1)
  p <- round(runif(2, min=0.1, max=0.9), 1)
  if(p[1] >= p[2])
    next
  C <- round(qnorm(p, mean=mu, sd=sigma), 1)
  
  Q <- quote(search(ipnorm, ipnorm(C[1L], C[2L], mu, sigma^2L), .S, .R, .P, .E))
  S <- findall(Q, options=list(preproc=as.rolog), env=environment())
  if(length(S) == 0)
    stop("No solutions found.")

  R <- sapply(S, FUN="[[", "R")
  P <- sapply(S, FUN=function(s) all(expert(s$P)))

  # Correct solution(s) should differ from incorrect ones.
  if(any(R[P] %in% R[!P]))
    next
  
  # Todo: couple bugs for z1 and z2, maybe use context(z1, ...) and 
  # context(z2, ...)
  
  # Todo: several incorrect solutions match to < 0.001 and 1. Collapse into
  # one option, and collect feedback for all of them.
  # if(any(duplicated(R)))
  #   next

  # Todo: Local definition of user:math_hook/2 overrides weak import from mathml
  # Todo: copy to lpnorm
  # Todo: copy to upnorm
  break
}

questions <- character(length(S))
solutions <- logical(length(S))
explanations <- character(length(S))

for(i in 1:length(S))
{
  Si <- S[[i]]$S
  Ri <- S[[i]]$R
  Pi <- S[[i]]$P
  Ei <- S[[i]]$E

  questions[i] <- Ri
  solutions[i] <- all(expert(Pi))
  e1 <- sprintf("The result matches the following expression: %s\n", mathml(Si))
  e2 <- paste(feedback(task, Pi), collapse=" ")
  e3 <- paste(feedback(task, Ei), collapse=" ")
  if(e3 != "")
    e3 <- paste("Extra information: ", e3)
  explanations[i] <- paste(e1, e2, e3)
}

o <- sample(1:length(S))
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]
S <- S[o]
```

Question
========
We consider the Normal
distribution $X \sim N\left(\mu=`r mu`, \sigma^2=`r sigma^2`\right)$. 

How many realizations are between $`r C[1L]`$ and $`r C[2L]`$?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup="markdown")
```

Solution
========
The proportion is calculated by: `r mathml(S[[which(solutions)[1]]]$S)`

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup="markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions, single=TRUE)`
exname: ipnorm
